CREATE TABLE IF NOT EXISTS rooms (
    room_id SERIAL PRIMARY KEY,    
    name_room VARCHAR(50) ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
